language: node_js
node_js:
  - 9
  - 8
after_success:
  - npm install --no-save nyc
  - npm install --no-save coveralls
  - nyc ava
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
