language: node_js
node_js:
  - 9
  - 8
after_success:
  - npm install --no-save nyc && npm install --no-save coveralls && ./node_modules/nyc/bin/nyc.js --reporter=lcov --reporter=text-lcov npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
